### ISSUE TITLE
 Installation location of utils in colabfold-conda

### ISSUE THREAD

**Issue by baba-hashimoto** [hongliangduan/HighFold#4]
Thank you for developing such a wonderful program. I tried to install it to reproduce it, but I didn't understand how to handle the utils folder. It may not work just by moving the folder. If there was someone who had previously succeeded in running it, I would be happy if you could share the information.

**Comment by YanapatJ** [comment]
I just replaced the original alphafold, colabfold, and utils folders in /localcolabfold/colabfold-conda/lib/python3.10/site-packages/ with the ones from Highfold, and it works for me.

**Comment by YanapatJ** [comment]
However, I am not 100% sure if that's the right way to do it or not.

**Comment by baba-hashimoto** [comment]
Thanks for your answer. I was hesitant to copy it because there was no utils in /localcolabfold/colabfold-conda/lib/python3.10/site-packages/. After copying it, I fixed some bugs (importing PDBData as SCOPData from Bio.Data)
and it started working. On the other hand, I ran the following, but the peptides did not take a cyclic structure.
>fasta
SAKIDNLD:
SSPGIWLDCTHLEGKVILVAVHVASGYIEAVIPAETGQETAYFLLLAGRWPVKTHDNGSNFTSTTVKAACWWAGIQEDGIPYNPQSQGVIESMNKELKKIIGQVRDQAEHLKTAVQMAVFIHNHKRKGYSAGERIVIIATDIQ:
SSPGIWLDCTHLEGKVILVAVHVASGYIEAVIPAETGQETAYFLLLAGRWPVKTHDNGSNFTSTTVKAACWWAGIQEDGIPYNPQSQGVIESMNKELKKIIGQVRDQAEHLKTAVQMAVFIHNHKRKGYSAGERIVIIATDIQ


Have you created a ring structure in your calculations?

**Comment by YanapatJ** [comment]
I haven't tried that. I only did
fasta
>1
XXXXXX

and it works

**Comment by baba-hashimoto** [comment]
Thank you for your reply. When I ran it with the same input file, I got the following error.

2024-11-06 11:54:41,499 reranking models by 'plddt' metric
2024-11-06 11:54:41,552 Warning: importing 'simtk.openmm' is deprecated. Import 'openmm' instead.
Traceback (most recent call last):
File “/home/localcolabfold/localcolabfold/colabfold-conda/bin/colabfold_batch”, line 8, in <module>
sys.exit(main())
File “/home/localcolabfold/localcolabfold/HighFold/colabfold/batch.py”, line 2044, in main
run(
File “/home/localcolabfold/localcolabfold/HighFold/colabfold/batch.py”, line 1716, in run
results = predict_structure(
File “/home/localcolabfold/localcolabfold/HighFold/colabfold/batch.py”, line 584, in predict_structure
pdb_lines = relax_me(pdb_lines=unrelaxed_pdb_lines[key], use_gpu=use_gpu_relax)
File “/home/localcolabfold/localcolabfold/HighFold/colabfold/batch.py”, line 359, in relax_me
relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=pdb_obj)
File “/home/localcolabfold/localcolabfold/HighFold/alphafold/relax/relax.py”, line 62, in process
out = amber_minimize.run_pipeline(
File “/home/localcolabfold/localcolabfold/HighFold/alphafold/relax/amber_minimize.py”, line 470, in run_pipeline
_check_residues_are_well_defined(prot)
File “/home/localcolabfold/localcolabfold/HighFold/alphafold/relax/amber_minimize.py”, line 145, in _check_residues_are_well_defined
raise ValueError("Amber minimization can only be performed on proteins with”
ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.
When I ran it without --amber, it worked, but the pdb file was like the following.
MODEL 1 
TER 1 UNK A 6 
ENDMDL 
END 
When you ran it, did it output the coordinates of some kind of cyclic peptide?

**Comment by YanapatJ** [comment]
check issue #2
